### PR TITLE
Animating contentScrollView jump.

### PR DESCRIPTION
**Pull request by Netwolf**
To fix the jump error i animated the contentScrollView jump.

### CODE REVIEW

**Comment by yysskk** [comment]
Hi, @Netwolf. 
It doesn't need to animate in some cases , so can you do like this?

```
    public func jump(to index: Int, animated: Bool) {

        if let tabView = tabView, let contentScrollView = contentScrollView {
            tabView.jump(to: index)
            contentScrollView.jump(to: index, animated: animated)
        }
    }
```

**Comment by Netwolf** [comment]
Ok, im doing it now.

**Comment by Netwolf** [comment]
Done, can you check for me please?

**Comment by yysskk** [comment]
Good work 👍

**Pull request merged**
